### ISSUE TITLE
More than one repository not working

### ISSUE THREAD

**Issue by ytsejam78** [ba-st/Sagan#19]
When using more than one repository, during #configureMappingsIn: the first repository setups the session causing the descriptor system to perform a validation (see method: GlorpSession>>system:).
Due to how Sagan's configurable descriptor system works, this causes only the first repository's tables, class descriptors and mappings to be created. The rest only exist as definitions which are never evaluated because of lazy variable initializations.

**Comment by gcotelli** [comment]
Fixed by #20
