### ISSUE TITLE
Update problem with session pool

### ISSUE THREAD

**Issue by ytsejam78** [ba-st/Sagan#37]
If update:with: is performed in a different session from the one used to read the original object, it fails as Glorp tries to do an insert instead of an update.

Problem is already documented in this test:
PooledRDBMSRepositoryProviderTest>>testUpdateWithOutsideTransactWillFail

Workaround for now is to re-read the object before updating it, within the same transaction to ensure same session is used.
For example, update method for a trade registration system:

```smalltalk
updateTrade: originalTrade with: updatedTrade

	^trades transact: [:session |
		trades
			withOneMatching: [:trade :builder | builder does: trade equal: originalTrade]
			do: [:trade | trades update: trade with: updatedTrade]
			else: [ObjectNotFound signal: ('<1p> was not found.' expandMacrosWith: originalTrade)]]
```

**Comment by fortizpenaloza** [comment]
Yes, and what are you suggesting? I was wondering last time I got into this same "problem", if it is better to encapsulate the re-read within Sagan 🤔
