### ISSUE TITLE
Ease running tests in development with different db motors using docker-compose

### ISSUE THREAD

**Issue by jvanecek** [ba-st/Sagan#54]
Currently, running tests with a specific db it's a bit unconfortable as to deploy a db using the [scripts](https://github.com/ba-st/Sagan/tree/release-candidate/scripts), one needs to remember which environment variables needs to be set. 

This can be easily solved by adding a docker-compose that has the same set up as the scripts.

**Comment by gcotelli** [comment]
Fixed by #55
